/**
 * Auto-generated Cloudflare Worker with SSR modules
 * Generated at: {{GENERATED_AT}}
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated by scripts/generate-imports.js
 */

import { injectAssets, normalizePublicPath } from "sxo/src/js/server/utils/inject-assets.js";
import { routeMatch } from "sxo/src/js/server/utils/route-match.js";
import routes from "../dist/server/routes.json" with { type: "json" };

// Static imports for all server modules (required for Cloudflare Workers)
// {{IMPORTS}}

// Map jsx paths to their imported modules
const moduleMap = {
    // {{MODULE_MAP}}
};

export default {
    async fetch(request, env) {
        const url = new URL(request.url);

        // Route via manifest: use routes.json + routeMatch() as the source of truth
        const match = routeMatch(url.pathname, routes);
        if (!match) {
            return new Response("Not Found", { status: 404 });
        }
        if (match.invalid) {
            return new Response("Invalid parameters", { status: 400 });
        }

        const { route, params } = match;

        // If this page was generated, serve pre-rendered HTML from assets
        if (route.generated === true && route.filename) {
            try {
                const origin = new URL(request.url).origin;
                const assetUrl = new URL(`${origin}/${route.filename}`);
                const html = await env.ASSETS.fetch(assetUrl).then((res) => {
                    if (!res.ok) throw new Error(`Failed to fetch: ${route.filename}`);
                    return res.text();
                });
                return new Response(html, {
                    status: 200,
                    headers: {
                        "content-type": "text/html; charset=utf-8",
                        "cache-control": "public, max-age=300",
                    },
                });
            } catch (e) {
                console.error(`Error loading generated page ${route.filename}:`, e);
                // Fall through to SSR
            }
        }

        // Get the module from the static import map
        const mod = moduleMap[route.jsx];
        if (!mod) {
            console.error(`Module not found in map for: ${route.jsx}`);
            return new Response("Internal Server Error", { status: 500 });
        }

        const render = mod.default || mod.jsx;

        if (typeof render !== "function") {
            return new Response("Internal Server Error", { status: 500 });
        }

        let html = await render(params);
        const isHtml = /^<html[\s>]/i.test(html);

        // Inject built assets for non-generated routes
        const publicPath = normalizePublicPath(env?.PUBLIC_PATH ?? "/");
        if (route.assets && typeof route.assets === "object" && isHtml) {
            html = injectAssets(html, route.assets, publicPath);
        }

        const page = isHtml ? `<!doctype html>\n${html}` : html;

        return new Response(page, {
            status: 200,
            headers: {
                "content-type": "text/html; charset=utf-8",
                "cache-control": "public, max-age=0, must-revalidate",
            },
        });
    },
};
